import React, { useState, useCallback } from 'react';
import { UploadSection } from './components/UploadSection';
import { PhotoCard } from './components/PhotoCard';
import { PHOTO_STYLES } from './constants';
import { GeneratedImage, ProcessingStatus } from './types';
import { generateStyledPhoto } from './services/geminiService';
import { Sparkles, Camera, RefreshCw } from 'lucide-react';

const App: React.FC = () => {
  const [originalImage, setOriginalImage] = useState<string | null>(null);
  const [generatedImages, setGeneratedImages] = useState<GeneratedImage[]>([]);
  const [status, setStatus] = useState<ProcessingStatus>(ProcessingStatus.IDLE);

  const resetApp = () => {
    setOriginalImage(null);
    setGeneratedImages([]);
    setStatus(ProcessingStatus.IDLE);
  };

  const handleImageSelected = useCallback(async (base64Image: string) => {
    setOriginalImage(base64Image);
    setStatus(ProcessingStatus.PROCESSING);
    
    // Initialize placeholders
    const initialPlaceholders: GeneratedImage[] = PHOTO_STYLES.map(style => ({
      id: style.id,
      styleId: style.id,
      styleName: style.name,
      imageUrl: null,
      loading: true
    }));
    
    setGeneratedImages(initialPlaceholders);

    // Process images in parallel but update state independently
    PHOTO_STYLES.forEach(async (style) => {
      try {
        const generatedBase64 = await generateStyledPhoto(base64Image, style.prompt);
        
        setGeneratedImages(prev => prev.map(img => 
          img.styleId === style.id 
            ? { ...img, imageUrl: generatedBase64, loading: false } 
            : img
        ));
      } catch (error) {
        setGeneratedImages(prev => prev.map(img => 
          img.styleId === style.id 
            ? { ...img, loading: false, error: 'Failed to generate' } 
            : img
        ));
      }
    });

    // We don't strictly wait for all to finish to change global status, 
    // but we can assume 'COMPLETED' when the user has uploaded.
    // The individual loaders handle the granular status.
    setStatus(ProcessingStatus.COMPLETED);

  }, []);

  return (
    <div className="min-h-screen bg-black text-white font-sans selection:bg-indigo-500/30">
      
      {/* Navbar */}
      <nav className="border-b border-zinc-800 bg-zinc-950/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center space-x-3">
              <div className="p-2 bg-indigo-600 rounded-lg">
                <Camera className="w-5 h-5 text-white" />
              </div>
              <span className="text-xl font-bold tracking-tight bg-gradient-to-r from-white to-zinc-400 bg-clip-text text-transparent">
                Nano Studio
              </span>
            </div>
            {originalImage && (
              <button 
                onClick={resetApp}
                className="flex items-center space-x-2 text-sm text-zinc-400 hover:text-white transition-colors"
              >
                <RefreshCw className="w-4 h-4" />
                <span>New Project</span>
              </button>
            )}
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        
        {/* Header Section */}
        {!originalImage && (
          <div className="text-center mb-12 animate-fade-in-up">
            <h1 className="text-4xl md:text-5xl font-extrabold mb-6 tracking-tight">
              AI Portrait Transformation
            </h1>
            <p className="text-lg text-zinc-400 max-w-2xl mx-auto mb-8">
              Upload one photo and instantly get 6 professional styles generated by Gemini Nano Banana. From corporate headshots to vintage Hong Kong aesthetics.
            </p>
            <div className="flex items-center justify-center space-x-2 text-indigo-400 text-sm font-medium bg-indigo-400/10 py-1 px-3 rounded-full w-fit mx-auto border border-indigo-400/20">
              <Sparkles className="w-3 h-3" />
              <span>Powered by gemini-2.5-flash-image</span>
            </div>
          </div>
        )}

        {/* Upload Section */}
        {!originalImage && (
          <div className="max-w-xl mx-auto">
            <UploadSection 
              onImageSelected={handleImageSelected} 
              isProcessing={status === ProcessingStatus.PROCESSING} 
            />
          </div>
        )}

        {/* Results Section */}
        {originalImage && (
          <div className="space-y-12 animate-fade-in">
            {/* Source Image Review (Small) */}
            <div className="flex flex-col items-center">
               <div className="relative group w-32 h-32 rounded-full overflow-hidden border-4 border-zinc-800 shadow-xl mb-4">
                 <img src={originalImage} alt="Original" className="w-full h-full object-cover" />
                 <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                   <span className="text-xs font-medium">Original</span>
                 </div>
               </div>
               <h2 className="text-xl font-semibold text-zinc-200">Generating Your Portfolio</h2>
               <p className="text-zinc-500 text-sm mt-1">Creating 6 unique styles...</p>
            </div>

            {/* Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8">
              {generatedImages.map((image) => (
                <PhotoCard key={image.id} item={image} />
              ))}
            </div>
          </div>
        )}

      </main>

      {/* Footer */}
      <footer className="border-t border-zinc-900 mt-20 py-8 bg-zinc-950">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p className="text-zinc-600 text-sm">
            AI Generated images may vary. Using Gemini 2.5 Flash Image Model.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default App;